name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: ["closed"]

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      run: echo "DATABASE_URL=${{ secrets.POSTGRES_RDS_URL }}" > .env

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag krizz23/sms-backend:actions

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
      run: docker push krizz23/sms-backend:actions

    - name: Run sshpass commands
      uses: matheusvanzan/sshpass-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        password: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          sudo docker ps -q --filter "name=sms-backend" | xargs -r sudo docker stop'
          sleep 2
          sudo docker ps -aq --filter "name=sms-backend" | xargs -r sudo docker rm -fv
          sleep 5
