name: Docker Image CI

on:
  workflow_dispatch: # Manually run the workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: ["merged"]

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make envfile
      run: echo "DATABASE_URL=${{ secrets.POSTGRES_RDS_URL }}" > .env;
           echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env;
           echo "AUTH0_API_AUDIENCE=${{ secrets.AUTH0_API_AUDIENCE }}" >> .env;
           echo "ALGORITHMS=${{ secrets.AUTH0_ALGORITHMS }}" >> .env;
           echo "ISSUER=${{ secrets.AUTH0_ISSUER }}" >> .env;

    - name: Build the Docker image
      run: docker build -t krizz23/sms-backend:actions .

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
      run: docker push krizz23/sms-backend:actions

  Deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy in EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      run: |
        echo "$EC2_PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST '
          #Now we have got the access of EC2 and we will start the deploy .
          #Stop the running container
          sudo docker ps -q --filter "name=sms-backend" | xargs -r sudo docker stop
          sleep 2
          #Remove the container (only to be sure)
          sudo docker ps -aq --filter "name=sms-backend" | xargs -r sudo docker rm -fv
          sleep 5
          # Remove unused data
          sudo docker system prune -fa --volumes
          #Pull and run the latest image
          sudo docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull krizz23/sms-backend:actions
          sudo docker run -d -p 8000:8000 --name sms-backend krizz23/sms-backend:actions
        '